name: pueprint
description: A Flutter package to make flows and single pages much easier to lay out and style 
version: 0.0.8
repository: https://github.com/theweiweiway/pueprint

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
