name: pueprint
description: A new Flutter package project.
version: 0.0.2
repository: https://github.com/theweiweiway/pueprint

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
